arrive_afterhours_meet_entry([Scene entrypoint]) --> arrive_afterhours_meet_navigate[Leaving my room, going to meeting place] --> arrive_afterhours_meet_chat[Chatting with antagonist -- TODO] --> arrive_afterhours_meet_leave[Leaving, going back to my room] --> arrive_afterhours_meet_exit([Scene exitpoint])
