arrive_entry([Scene entrypoint]) --> arrive_saysoon[I hear 'arriving soon' and explain how I got here]
arrive_saysoon --> arrive_parking[My pod is parking at spaceship]
arrive_parking --> arrive_meet_capn[I meet spaceship's captain]
arrive_meet_capn --> arrive_capn_says_explore[Captain tells me to explore ship]
arrive_capn_says_explore --> arrive_exit([Scene exitpoint])
