logistics_breaks_room_entry([Scene entrypoint]) --> logistics_breaks_room_robot_arrives[Robot arrives with weird thing] --> logistics_breaks_room_robot_report[I press 'report' button and hear email notification] --> logistics_breaks_room_spam[Many emails arrive with reports] --> logistics_breaks_room_leaving[I leave my room] --> logistics_breaks_room_exit([Scene exitpoint])
